//! tokens_tab.rs — PoC 4:design-token 化的樣式層。
//! 上半:token rails(SCSS 生成的變數,體)以 swatch 呈現。
//! 下半:模擬 AI 生成的 style spec(JSON)——只能引用 token;
//!       raw CSS / 未授權屬性在驗證層被拒(樣式的 capability sandbox)。

use crate::tokens::{style_of, COLORS};
use leptos::prelude::*;

const DEFAULT_SPEC: &str =
    r#"{"background":"surface-3","color":"success","padding":"5","radius":"2","font":"3"}"#;

#[component]
pub fn TokensPoc() -> impl IntoView {
    let spec_text = RwSignal::new(DEFAULT_SPEC.to_string());
    let style_str = RwSignal::new(String::new());
    let err = RwSignal::new(String::new());

    let run = move |src: &str| match serde_json::from_str::<
        serde_json::Map<String, serde_json::Value>,
    >(src)
    {
        Ok(spec) => match style_of(&spec) {
            Ok(s) => {
                style_str.set(s);
                err.set(String::new());
            }
            Err(e) => err.set(e),
        },
        Err(e) => err.set(format!("JSON parse failed: {e}")),
    };

    run(DEFAULT_SPEC); // 初始顯化一次

    let apply = move |_| run(&spec_text.get());
    let violate = move |_| {
        let bad = r##"{"color":"#ff0000","position":"fixed"}"##;
        spec_text.set(bad.to_string());
        run(bad);
    };

    view! {
        <p class="sub">
            "Style substance & function: SCSS generates the token rails at compile time (substance); an AI manifestation may only reference token combinations (function). "
            "Raw CSS values and unauthorized properties are rejected at the validation layer — isomorphic to the DSL's fetch() rejection: the style layer's import table."
        </p>

        <h2>"Token rails (generated by styles/tokens.scss, not modifiable by a manifestation)"</h2>
        <div class="swatches">
            {COLORS
                .iter()
                .map(|c| {
                    view! {
                        <div class="swatch" style=format!("background:var(--tk-color-{c})")>
                            <span>{*c}</span>
                        </div>
                    }
                })
                .collect_view()}
        </div>

        <h2>"Manifestation (a simulated AI-generated style spec — may only reference tokens)"</h2>
        <textarea class="tok-spec" rows="3"
            prop:value=move || spec_text.get()
            on:input=move |ev| spec_text.set(event_target_value(&ev))></textarea>
        <div class="tok-row">
            <button class="apply tok-apply" on:click=apply>"Apply spec"</button>
            <button class="tok-violate" on:click=violate>"try to escalate (raw CSS + position)"</button>
        </div>
        <Show when=move || !err.get().is_empty()>
            <div class="tok-err">{move || err.get()}</div>
        </Show>

        <div class="tok-preview" style=move || style_str.get()>
            "Preview card — every style on me is a var(--tk-*), not a single raw value."
            <br />
            <code style="font-size:var(--tk-font-1);opacity:.75">
                {move || style_str.get()}
            </code>
        </div>
    }
}
